### ISSUE TITLE
Implement CI

### ISSUE THREAD

**Issue by gatheluck** [cvpaperchallenge/Crux#14]
## Why
Now CI job (Github Action) is not implemented. But now all docker and compose files are ready. So let's implement CI.

## Definition of Done
CI job is implemented which should fulfill following conditions:
- The job should run when:
  -  merge request to develop branch is created
  - PR is merged to develop branch
- The job should be run over both frontend and backend.
- In the CI job following commands should be kicked:
  - `make lint`
  - `make test`  

## How
write YAML file and Docker files for CI job under `.github/workflows`. You can refer original CI used in [original YAML file Ascender](https://github.com/cvpaperchallenge/Ascender/blob/develop/.github/workflows/lint-and-test.yaml).

## Note
- Blocked by #11 .
- It is OK to ignore Cache.

**Comment by YoshikiKubotani** [comment]
It actually took 7.5 hours to finish this task (including the time to get used to the GitHub Actions basic usage).
So the point should probably be updated to 15 (or 11 in between).
