### ISSUE TITLE
Try to use the base project gpt-pdf-summarizer

### ISSUE THREAD

**Issue by YoshikiKubotani** [cvpaperchallenge/Crux#3]
# Why
To see whether to upload pdfs and summarize them on https://github.com/zerebom/gpt-pdf-summarizer project

# Definition of Done
- Upload some pdfs
- Download summarized pdfs
- Check and analyze the detailed code of the project above
- Results will be reported under this issue.

# How
- Try it out on the project page

**Comment by YoshikiKubotani** [comment]
# Report

At first, I met an error of the `openai.api_key` not keeping the API key value.  But the code finally worked by hardcoding it.
The repo itself seems to be made under the instruction of chatGPT, meaning that it has redundant or unnecessary parts.
Also, as their prompt is pretty simple (i.e. `下記文章を日本語で{max_length}字で要約して:\n\n{text}\n`), we need to think up the better prompt to generate the better summarization.
For the token length problem, they just split the paper text into some chunks and generate summarization by applying the prompt above repeatedly.  If we have access to the GPT4, this would not be an issue.

**Comment by gatheluck** [comment]
Thank you for summarizing your experiments! It's really helpful! About prompt part, let's do "prompt engineering" in the future step.

I think now this ticket is done. So let me close this issue.
