### ISSUE TITLE
[Backend] Implement a pdf reader

### ISSUE THREAD

**Issue by YoshikiKubotani** [cvpaperchallenge/Crux#7]
# Why

Crux project reads pdfs and summarizes them by using open AI API.  As a first step, implementing a pdf reader is necessary.

# Definition of Done

- Load the user inputs as a `.pdf` form.
- Come up with LLM prompts to get well-structured summarized sentences
-  Allow the user to download the outputs as a `.json` form.

# How
- **Other task tickets will be created to make this story finished**
- Use one of the pdf reader libraries (e.g. [pypdf](https://github.com/py-pdf/pypdf), [pdfplumber](https://github.com/jsvine/pdfplumber))
- Refer to [this article](https://huyenchip.com/2023/04/11/llm-engineering.html) for prompt engineering

**Comment by gatheluck** [comment]
I realized that [LlamaIndex](https://gpt-index.readthedocs.io/en/latest/#) has native support to load from PDF, and convert into docs object. Maybe we should use this feature because LlamaIndex also has native connection between GPT and LangChain.

**Comment by YoshikiKubotani** [comment]
This [github repo](https://github.com/Anil-matcha/ChatPDF/tree/main) is also helpful to catch the point of how to use langchain for PDF reader.
